# Generated by Django 4.1.7 on 2023-04-05 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('metadata', models.JSONField(blank=True, help_text='Metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata_id', models.AutoField(help_text='The tenant chats ID UUID for all chats.', primary_key=True, serialize=False)),
                ('tenant_id', models.JSONField(help_text='Display name of the tenant')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at', '-metadata'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('metadata', models.JSONField(blank=True, help_text='Metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.AutoField(help_text='The tenant chats ID UUID for all chats.', primary_key=True, serialize=False)),
                ('tenant_name', models.CharField(help_text='name of the company', max_length=30)),
                ('industry', models.CharField(help_text='industry of the company', max_length=30)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at', '-metadata'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('metadata', models.JSONField(blank=True, help_text='Metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_id', models.AutoField(help_text='The tenant chats ID UUID for all chats.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='name of the product', max_length=30)),
                ('description', models.TextField(help_text='description of the product', max_length=200)),
                ('price', models.CharField(help_text='price of the product', max_length=30)),
                ('tenant_id', models.ForeignKey(help_text='Display name of the tenant', on_delete=django.db.models.deletion.CASCADE, to='core_engine_tenant_management_app.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at', '-metadata'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('metadata', models.JSONField(blank=True, help_text='Metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_id', models.AutoField(help_text='Address id of the tenant', primary_key=True, serialize=False)),
                ('billing_details_id', models.CharField(help_text='Billing details of tyhe tenant', max_length=30)),
                ('city', models.CharField(help_text='City which the tenant comes from', max_length=30)),
                ('country', models.CharField(help_text='Country of yhe tenant', max_length=30)),
                ('postal_code', models.CharField(help_text='Postal code of the tenant', max_length=30)),
                ('state', models.CharField(help_text='Statement which the tenant comes from', max_length=30)),
                ('payment_number', models.CharField(help_text='If for mobile transaction - the phone number to use', max_length=30)),
                ('tenant_id', models.OneToOneField(help_text='Display name of the tenant', on_delete=django.db.models.deletion.CASCADE, to='core_engine_tenant_management_app.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at', '-metadata'],
                'abstract': False,
            },
        ),
    ]
