# Generated by Django 4.1.7 on 2023-04-06 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine_tenant_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='tenant_id',
            field=models.AutoField(help_text='The tenant chats ID.', primary_key=True, serialize=False),
        ),
    ]
