# Generated by Django 4.1.7 on 2023-04-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine_tenant_management_app', '0002_alter_tenant_tenant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='DateField',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='DateField',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='DateField',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='DateField',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='created_at',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='created_at',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
