# Generated by Django 4.1.7 on 2023-04-16 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine_tenant_management_app', '0003_address_datefield_metadata_datefield_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='DateField',
            new_name='date_time_created_at',
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='DateField',
            new_name='date_time_created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='DateField',
            new_name='date_time_created_at',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='DateField',
            new_name='date_time_created_at',
        ),
    ]
