# Generated by Django 4.1.7 on 2023-05-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine_tenant_management_app', '0004_rename_datefield_address_date_time_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='tenant_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tenant_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
