# Generated by Django 4.1.7 on 2023-05-01 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine_tenant_management_app', '0005_tenant_tenant_email_tenant_tenant_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='tenant_email',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='tenant_phone',
        ),
    ]
