# Generated by Django 4.1.7 on 2023-04-16 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine_users_profile_app', '0002_adminprofile_datefield_clientprofile_datefield_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminprofile',
            old_name='DateField',
            new_name='date_time_created_at',
        ),
        migrations.RenameField(
            model_name='clientprofile',
            old_name='DateField',
            new_name='date_time_created_at',
        ),
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='DateField',
            new_name='date_time_created_at',
        ),
    ]
