# Generated by Django 4.1.7 on 2023-04-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine_users_profile_app', '0003_rename_datefield_adminprofile_date_time_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='age',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
