# Generated by Django 4.1.7 on 2023-04-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine_users_profile_app', '0004_clientprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='gender',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
