# Generated by Django 4.1.7 on 2023-04-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine_users_profile_app', '0005_clientprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
