# Generated by Django 4.1.7 on 2023-04-05 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_engine_chat_app', '0001_initial'),
        ('core_engine_tenant_management_app', '0001_initial'),
        ('core_engine_tenant_users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientchats',
            name='client_id',
            field=models.ForeignKey(help_text='Display name of the client', on_delete=django.db.models.deletion.CASCADE, to='core_engine_tenant_users_app.client'),
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_owner',
            field=models.ForeignKey(help_text='Display name of the client', on_delete=django.db.models.deletion.CASCADE, to='core_engine_tenant_users_app.client'),
        ),
        migrations.AddField(
            model_name='chat',
            name='guest_client',
            field=models.ForeignKey(blank=True, help_text='Invited participant in the chat', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_client', to='core_engine_tenant_users_app.client'),
        ),
        migrations.AddField(
            model_name='chat',
            name='tenant',
            field=models.ForeignKey(help_text='Display name of the tenant', on_delete=django.db.models.deletion.CASCADE, to='core_engine_tenant_management_app.tenant'),
        ),
    ]
