# Generated by Django 4.1.7 on 2023-04-06 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine_tenant_users_app', '0002_alter_admin_tenant_id'),
        ('core_engine_chat_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_owner',
            field=models.ForeignKey(help_text='Display name of the client', on_delete=django.db.models.deletion.CASCADE, related_name='chat_owner', to='core_engine_tenant_users_app.client'),
        ),
    ]
