# Generated by Django 4.1.7 on 2023-04-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine_chat_app', '0003_alter_chat_chat_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='DateField',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='clientchats',
            name='DateField',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='DateField',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantchats',
            name='DateField',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clientchats',
            name='created_at',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tenantchats',
            name='created_at',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
