# Generated by Django 4.1.7 on 2023-04-16 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine_chat_app', '0004_chat_datefield_clientchats_datefield_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='DateField',
            new_name='date_time_created_at',
        ),
        migrations.RenameField(
            model_name='clientchats',
            old_name='DateField',
            new_name='date_time_created_at',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='DateField',
            new_name='date_time_created_at',
        ),
        migrations.RenameField(
            model_name='tenantchats',
            old_name='DateField',
            new_name='date_time_created_at',
        ),
    ]
