# Generated by Django 4.1.7 on 2023-04-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine_chat_app', '0006_message_escalated'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='channel',
            field=models.CharField(choices=[('Mobile', 'Mobile'), ('Website', 'Website')], help_text='Channel from which message was sent', max_length=200, null=True),
        ),
    ]
