# Generated by Django 4.1.7 on 2023-04-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine_chat_app', '0007_message_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='topic',
            field=models.CharField(choices=[('Mobile', 'Mobile'), ('Website', 'Website')], help_text='Message topic', max_length=200, null=True),
        ),
    ]
