# Generated by Django 4.1.7 on 2023-04-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine_chat_app', '0008_message_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='client_satisfaction',
            field=models.BooleanField(default=False, help_text='Whether client is satisfied or not', null=True),
        ),
    ]
