# Generated by Django 4.2.1 on 2023-06-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_engine_chat_app", "0009_chat_client_satisfaction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chat",
            old_name="tenant",
            new_name="tenant_id",
        ),
        migrations.AddField(
            model_name="chat",
            name="iva_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable or disable whether the virtual assistant should talk to a client",
            ),
        ),
    ]
