# Generated by Django 4.1.7 on 2023-05-01 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_engine_tenant_management_app', '0005_tenant_tenant_email_tenant_tenant_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.CharField(choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Premium', 'Premium')], default='Basic', max_length=16)),
                ('quota', models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('BiAnnally', 'BiAnnally'), ('Annually', 'Annually')], default='Monthly', max_length=16)),
                ('is_valid', models.BooleanField(default=False)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core_engine_tenant_management_app.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant_ref', models.CharField(max_length=32, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=128, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('complete', models.BooleanField(default=False)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('payment_payload', models.JSONField(blank=True, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_engine_payments_app.subscription')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
