# Generated by Django 4.1.7 on 2023-04-05 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_engine_community_app', '0001_initial'),
        ('core_engine_tenant_management_app', '0001_initial'),
        ('core_engine_tenant_users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='client_id',
            field=models.ForeignKey(help_text='Display name of the client', on_delete=django.db.models.deletion.CASCADE, to='core_engine_tenant_users_app.client'),
        ),
        migrations.AddField(
            model_name='issue',
            name='community_id',
            field=models.ForeignKey(help_text='Display name of the community', on_delete=django.db.models.deletion.CASCADE, to='core_engine_community_app.community'),
        ),
        migrations.AddField(
            model_name='event',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_engine_tenant_users_app.client'),
        ),
        migrations.AddField(
            model_name='event',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_engine_community_app.community'),
        ),
        migrations.AddField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Members of the community', to='core_engine_tenant_users_app.client'),
        ),
        migrations.AddField(
            model_name='community',
            name='tenant_id',
            field=models.ForeignKey(help_text='Display name of the tenant', on_delete=django.db.models.deletion.CASCADE, to='core_engine_tenant_management_app.tenant'),
        ),
        migrations.AddField(
            model_name='comment',
            name='client',
            field=models.ForeignKey(help_text='Display name of the client', on_delete=django.db.models.deletion.CASCADE, to='core_engine_tenant_users_app.client'),
        ),
        migrations.AddField(
            model_name='comment',
            name='dislikes',
            field=models.ManyToManyField(blank=True, help_text='Users who liked the comment', related_name='comment_dislikes', to='core_engine_tenant_users_app.client'),
        ),
        migrations.AddField(
            model_name='comment',
            name='issue',
            field=models.ForeignKey(help_text='Display name of the Issue', on_delete=django.db.models.deletion.CASCADE, to='core_engine_community_app.issue'),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, help_text='Users who liked the comment', related_name='comment_likes', to='core_engine_tenant_users_app.client'),
        ),
        migrations.AddField(
            model_name='comment',
            name='thread',
            field=models.ForeignKey(help_text='Display name of the Thread', on_delete=django.db.models.deletion.CASCADE, to='core_engine_community_app.thread'),
        ),
    ]
