# Generated by Django 4.1.7 on 2023-04-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine_tenant_users_app', '0002_alter_admin_tenant_id'),
        ('core_engine_community_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='community_name',
            field=models.CharField(blank=True, help_text='Display name of the community', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Members of the community', null=True, to='core_engine_tenant_users_app.client'),
        ),
    ]
