# Generated by Django 4.1.7 on 2023-04-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine_tenant_users_app', '0002_alter_admin_tenant_id'),
        ('core_engine_community_app', '0003_alter_community_community_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Members of the community', to='core_engine_tenant_users_app.client'),
        ),
    ]
