# Generated by Django 4.1.7 on 2023-04-16 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine_community_app', '0005_comment_datefield_community_datefield_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='DateField',
            new_name='date_time_created_at',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='DateField',
            new_name='date_time_created_at',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='DateField',
            new_name='date_time_created_at',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='DateField',
            new_name='date_time_created_at',
        ),
    ]
