# Generated by Django 4.1.7 on 2023-04-17 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine_community_app', '0007_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='community_id',
            field=models.ForeignKey(help_text='Display name of the Community', null=True, on_delete=django.db.models.deletion.CASCADE, to='core_engine_community_app.community'),
        ),
    ]
