# Generated by Django 4.1.7 on 2023-04-23 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine_tenant_management_app', '0004_rename_datefield_address_date_time_created_at_and_more'),
        ('core_engine_tenant_users_app', '0002_alter_admin_tenant_id'),
        ('core_engine_community_app', '0008_alter_rating_community_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='community_id',
            field=models.AutoField(help_text='The tenant community ID UUID.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='community',
            name='community_name',
            field=models.CharField(blank=True, help_text='Display name of the community.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the community.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Members of the community.', to='core_engine_tenant_users_app.client'),
        ),
        migrations.AlterField(
            model_name='community',
            name='tenant_id',
            field=models.ForeignKey(help_text='Display name of the tenant.', on_delete=django.db.models.deletion.CASCADE, to='core_engine_tenant_management_app.tenant'),
        ),
    ]
