# Generated by Django 4.1.7 on 2023-04-24 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine_community_app', '0009_alter_community_community_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='issue',
        ),
    ]
