# Generated by Django 4.1.7 on 2023-04-05 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_engine_tenant_management_app', '0001_initial'),
        ('core_engine_survey_app', '0001_initial'),
        ('core_engine_tenant_users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='target_audience',
            field=models.ManyToManyField(help_text='The target audience', to='core_engine_tenant_users_app.client'),
        ),
        migrations.AddField(
            model_name='survey',
            name='tenant_id',
            field=models.ForeignKey(help_text='Display name of the tenant', on_delete=django.db.models.deletion.CASCADE, to='core_engine_tenant_management_app.tenant'),
        ),
        migrations.AddField(
            model_name='response',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core_engine_tenant_users_app.client'),
        ),
        migrations.AddField(
            model_name='response',
            name='survey_id',
            field=models.ForeignKey(help_text='Display name of the tenant', on_delete=django.db.models.deletion.CASCADE, to='core_engine_tenant_management_app.tenant'),
        ),
    ]
