# Generated by Django 4.1.7 on 2023-04-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine_survey_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='DateField',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='DateField',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='created_at',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='created_at',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
