# Generated by Django 4.1.7 on 2023-04-16 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine_survey_app', '0003_response_datefield_survey_datefield_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='DateField',
            new_name='date_time_created_at',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='DateField',
            new_name='date_time_created_at',
        ),
    ]
