# Generated by Django 4.1.7 on 2023-04-22 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine_survey_app', '0004_rename_datefield_response_date_time_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='survey_id',
            field=models.ForeignKey(help_text='Display name of the tenant', on_delete=django.db.models.deletion.CASCADE, to='core_engine_survey_app.survey'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_topic',
            field=models.CharField(help_text='The survey topic', max_length=255),
        ),
    ]
