# Generated by Django 4.1.7 on 2023-04-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine_survey_app', '0006_alter_survey_target_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_questions',
            field=models.JSONField(blank=True, help_text='The survey questions', null=True),
        ),
    ]
