# Generated by Django 4.1.7 on 2023-04-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine_survey_app', '0008_alter_survey_target_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='survey_response',
            field=models.JSONField(blank=True, help_text='The survey response', null=True),
        ),
    ]
