# Generated by Django 4.1.7 on 2023-05-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_engine_survey_app', '0010_survey_survey_type_surveysubgroups_surveyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='end_day',
            field=models.DateField(blank=True, help_text='The end day of the survey', null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='start_day',
            field=models.DateField(blank=True, help_text='The start day of the survey', null=True),
        ),
    ]
