from .admin import AdminProfileRetrieveAPIView, AdminRetrieveUpdateAPIView

from .client import ClientProfileRetrieveAPIView, ClientRetrieveUpdateAPIView

from .employee import EmployeeProfileRetrieveAPIView, EmployeeRetrieveUpdateAPIView